server:
  port: 8080

spring:
  application:
    name: mirror-api
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
