package com.rehearsal.domain.session.model;

public enum SessionStatus {
  BRIEFING,
  CONTEXT_EXTRACTING,
  FOLLOW_UP_REQUIRED,
  TRANSFORMATION_READY,
  TRANSFORMATION_PREPARING,
  REHEARSAL_READY,
  REHEARSAL_PLAYING,
  FEEDBACK_GENERATING,
  RESULT_READY,
  COMPLETED,
  FAILED
}
